### ISSUE TITLE
Questions about the parameter freq_bins setting

### ISSUE THREAD

**Issue by Jin-Tao-208** [adbailey1/DepAudioNet_reproduction#6]
Hi Andrew,
I was a little confused about the default value of the freq_bins parameter in the config_1.py file. The default value you have set is **freq_bins=40**. If I understand correctly, the freq_bins should be the parameter of WINDOwed segments after FFT in STFT.In the definition, **frequency bins=framesize/2+1**(in your program the framesize here is denoted by the variable window_size if I understand correctly), if calculated this way **frequency bins=1024/2+1=513**. But you set the value of freq_bins to 40 in your program, and I wonder why?
Looking forward to your reply, thank you!
best
Stella

**Comment by adbailey1** [comment]
Hi Stella, 

Sorry about the confusion, when I mention freq_bins in the config file, I am explicitly talking about mel bins for either mel spectrogram, log mel spectrogram, or MFCC etc. 

I will make a note to change this in case of further confusion, thanks for letting me know. 

Kind regards, 

Andrew

**Comment by Jin-Tao-208** [comment]
> Hi Stella,
> 
> Sorry about the confusion, when I mention freq_bins in the config file, I am explicitly talking about mel bins for either mel spectrogram, log mel spectrogram, or MFCC etc.
> 
> I will make a note to change this in case of further confusion, thanks for letting me know.
> 
> Kind regards,
> 
> Andrew

Hi  Andrew
Make sense! I see. Thank you!
 
Best 
Stella

**Comment by adbailey1** [comment]
Hi Stella, 

No problem. 

Kind regards, 

Andrew
